### ISSUE TITLE
[EngAut] ReviewBot: Introduce more sophisticated approval rights

### ISSUE THREAD

**Issue by Bullrich** [paritytech/review-bot#101]
As mentioned in polkadot-fellows/runtimes#93

- Implement new logic, which will consider lower than 4 ranks into approval decision
- dismiss some approvals with new commits
- [optionally in this scope] notify some selected groups via specified communication channels for readiness for review

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/review-bot/pull/112
- [ ] https://github.com/paritytech/review-bot/issues/110
- [ ] https://github.com/paritytech/review-bot/issues/109
- [ ] polkadot-fellows/runtimes#93
- [ ] https://github.com/paritytech/opstooling/issues/174
- [ ] https://github.com/paritytech/review-bot/issues/92
```

**Comment by Bullrich** [comment]
The feature has been released in https://github.com/paritytech/review-bot/pull/113

https://github.com/polkadot-fellows/runtimes/pull/168 has been created to resolve https://github.com/polkadot-fellows/runtimes/issues/93

**Comment by mordamax** [comment]
weekly update: no updates from last week

**Comment by Bullrich** [comment]
Update: polkadot-fellows/runtimes#168 has been merged, updating review bot to 2.4.0
